[app]
ident = "unique_ident"
name = "My Appname"
version = "1.0"
requires = []
launcher = "my_base_file.py"
standalone = true             # Set this to false if you want to 
                              # run your app as pyTainer module,
                              # e.g. for communicating with other
                              # non-standalone apps.

[info]
author = "John Doe"
website = "http://example.com"

# Custom configuration variables. These vars can be directly edited in the pyTainer UI

[config.sleeptime]
title = "Sleeptime"
description = "How long should we sleep between each loop?"
type = "float"
value = 1.2

[config.greeting]
title = "Greeting"
description = "How shoud I greet you when the script starts?"
type = "string"
value = "Hello my friend!"


