[app]
ident = "unique_ident"
name = "My Appname"
version = "1.0"
requires = []
launcher = "my_base_file.py"
language = "python"           #You may leave this blank, if its not a python app. Or set it to python3.9, python3.11 a.s.o
args = ""                     #Commandline args that have to be passed to the script
standalone = true             # Set this to false if you want to 
                              # run your app as pyTainer module,
                              # e.g. for communicating with other
                              # non-standalone apps.

[requirements]
modules = []

[info]
author = "John Doe"
website = "http://example.com"

# Custom configuration variables. These vars can be directly edited in the pyTainer UI
# The 4 properties title, description, type, value MUST be defined.

[config.sleeptime]
title = "Sleeptime"
description = "How long should we sleep between each loop?"
type = "float"
value = 1.2

[config.greeting]
title = "Greeting"
description = "How shoud I greet you when the script starts?"
type = "string"
value = "Hello my friend!"


